services:
  backend:
    build: ./backend
    container_name: dropout-api
    ports:
      - "8001:8000"
    volumes:
      - ./backend/logs:/app/logs
      - ./XG:/app/XG
    environment:
      - DEBUG=True
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: dropout-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - backend

  teacher_portal:
    image: nginx:alpine
    container_name: dropout-teacher-portal
    ports:
      - "4000:80"
    volumes:
      - ./teacher-portal:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - backend